language: python
dist: xenial
python:    
  - "3.7"

services:
  - docker

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --rm -f "Dockerfile" -t "$DOCKER_USERNAME/waterqualitydss-test:latest" -t "$DOCKER_USERNAME/waterqualitydss-test:$TRAVIS_COMMIT" --target test .
  - docker build --rm -f "Dockerfile" -t "$DOCKER_USERNAME/waterqualitydss:latest" -t "$DOCKER_USERNAME/waterqualitydss:$TRAVIS_COMMIT" .

# command to run tests
script:
  - docker run --rm -it "$DOCKER_USERNAME/waterqualitydss-test:latest"

deploy:
  provider: script
  script:
    - docker push "$DOCKER_USERNAME/waterqualitydss:$TRAVIS_COMMIT"
    - docker push "$DOCKER_USERNAME/waterqualitydss-test:$TRAVIS_COMMIT"
